// Election details for all 105 elections in the dataset
// Sources: Wikipedia (see individual source URLs)
const ELECTION_DETAILS = [
  {
    "country": "Afghanistan",
    "year": 2019,
    "election_type": "Presidential",
    "incumbent_name": "Ashraf Ghani",
    "incumbent_party": "Independent",
    "incumbent_pct": 50.64,
    "challenger_name": "Abdullah Abdullah",
    "challenger_party": "Independent",
    "challenger_pct": 39.52,
    "electoral_system": "Presidential, two-round",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2019_Afghan_presidential_election"
  },
  {
    "country": "Argentina",
    "year": 2007,
    "election_type": "Presidential",
    "incumbent_name": "Cristina Fernández de Kirchner",
    "incumbent_party": "FPV",
    "incumbent_pct": 45.29,
    "challenger_name": "Elisa Carrió",
    "challenger_party": "ARI",
    "challenger_pct": 23.04,
    "electoral_system": "Presidential, qualified plurality",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2007_Argentine_general_election"
  },
  {
    "country": "Armenia",
    "year": 2008,
    "election_type": "Presidential",
    "incumbent_name": "Serzh Sargsyan",
    "incumbent_party": "Republican Party",
    "incumbent_pct": 52.86,
    "challenger_name": "Levon Ter-Petrosyan",
    "challenger_party": "Independent",
    "challenger_pct": 21.5,
    "electoral_system": "Presidential, two-round",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2008_Armenian_presidential_election"
  },
  {
    "country": "Australia",
    "year": 2019,
    "election_type": "Parliamentary",
    "incumbent_name": "Scott Morrison",
    "incumbent_party": "Liberal/National Coalition",
    "incumbent_pct": 51.53,
    "challenger_name": "Bill Shorten",
    "challenger_party": "ALP",
    "challenger_pct": 48.47,
    "electoral_system": "Parliamentary, preferential voting (two-party preferred)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2019_Australian_federal_election"
  },
  {
    "country": "Australia",
    "year": 2022,
    "election_type": "Parliamentary",
    "incumbent_name": "Scott Morrison",
    "incumbent_party": "Liberal/National Coalition",
    "incumbent_pct": 47.55,
    "challenger_name": "Anthony Albanese",
    "challenger_party": "ALP",
    "challenger_pct": 52.13,
    "electoral_system": "Parliamentary, preferential voting (two-party preferred)",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2022_Australian_federal_election"
  },
  {
    "country": "Benin",
    "year": 2011,
    "election_type": "Presidential",
    "incumbent_name": "Boni Yayi",
    "incumbent_party": "FCBE",
    "incumbent_pct": 53.14,
    "challenger_name": "Adrien Houngbédji",
    "challenger_party": "PRD",
    "challenger_pct": 35.64,
    "electoral_system": "Presidential, two-round",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2011_Beninese_presidential_election"
  },
  {
    "country": "Bolivia",
    "year": 2009,
    "election_type": "Presidential",
    "incumbent_name": "Evo Morales",
    "incumbent_party": "MAS",
    "incumbent_pct": 64.22,
    "challenger_name": "Manfred Reyes Villa",
    "challenger_party": "PPB-CN",
    "challenger_pct": 26.46,
    "electoral_system": "Presidential, qualified plurality",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2009_Bolivian_general_election"
  },
  {
    "country": "Bolivia",
    "year": 2014,
    "election_type": "Presidential",
    "incumbent_name": "Evo Morales",
    "incumbent_party": "MAS",
    "incumbent_pct": 61.36,
    "challenger_name": "Samuel Doria Medina",
    "challenger_party": "UD",
    "challenger_pct": 24.23,
    "electoral_system": "Presidential, qualified plurality",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2014_Bolivian_general_election"
  },
  {
    "country": "Bolivia",
    "year": 2020,
    "election_type": "Presidential",
    "incumbent_name": "Luis Arce",
    "incumbent_party": "MAS",
    "incumbent_pct": 55.11,
    "challenger_name": "Carlos Mesa",
    "challenger_party": "CC",
    "challenger_pct": 28.83,
    "electoral_system": "Presidential, qualified plurality",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2020_Bolivian_general_election"
  },
  {
    "country": "Botswana",
    "year": 2019,
    "election_type": "Parliamentary",
    "incumbent_name": "Mokgweetsi Masisi",
    "incumbent_party": "BDP",
    "incumbent_pct": 52.65,
    "challenger_name": "Duma Boko",
    "challenger_party": "UDC",
    "challenger_pct": 35.69,
    "electoral_system": "Parliamentary, first-past-the-post",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2019_Botswana_general_election"
  },
  {
    "country": "Botswana",
    "year": 2024,
    "election_type": "Parliamentary",
    "incumbent_name": "Mokgweetsi Masisi",
    "incumbent_party": "BDP",
    "incumbent_pct": 30.6,
    "challenger_name": "Duma Boko",
    "challenger_party": "UDC",
    "challenger_pct": 37.4,
    "electoral_system": "Parliamentary, first-past-the-post",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2024_Botswana_general_election"
  },
  {
    "country": "Brazil",
    "year": 2018,
    "election_type": "Presidential",
    "incumbent_name": "Fernando Haddad",
    "incumbent_party": "PT",
    "incumbent_pct": 44.87,
    "challenger_name": "Jair Bolsonaro",
    "challenger_party": "PSL",
    "challenger_pct": 55.13,
    "electoral_system": "Presidential, two-round",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2018_Brazilian_general_election"
  },
  {
    "country": "Brazil",
    "year": 2022,
    "election_type": "Presidential",
    "incumbent_name": "Jair Bolsonaro",
    "incumbent_party": "PL",
    "incumbent_pct": 49.1,
    "challenger_name": "Luiz Inácio Lula da Silva",
    "challenger_party": "PT",
    "challenger_pct": 50.9,
    "electoral_system": "Presidential, two-round",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2022_Brazilian_general_election"
  },
  {
    "country": "Bulgaria",
    "year": 2013,
    "election_type": "Parliamentary",
    "incumbent_name": "Boyko Borisov",
    "incumbent_party": "GERB",
    "incumbent_pct": 30.54,
    "challenger_name": "Sergei Stanishev",
    "challenger_party": "BSP (Coalition for Bulgaria)",
    "challenger_pct": 26.61,
    "electoral_system": "Parliamentary, proportional representation",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2013_Bulgarian_parliamentary_election"
  },
  {
    "country": "Bulgaria",
    "year": 2017,
    "election_type": "Parliamentary",
    "incumbent_name": "Boyko Borisov",
    "incumbent_party": "GERB",
    "incumbent_pct": 32.65,
    "challenger_name": "Korneliya Ninova",
    "challenger_party": "BSP",
    "challenger_pct": 27.2,
    "electoral_system": "Parliamentary, proportional representation",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2017_Bulgarian_parliamentary_election"
  },
  {
    "country": "Bulgaria",
    "year": 2021,
    "election_type": "Parliamentary",
    "incumbent_name": "Boyko Borisov",
    "incumbent_party": "GERB",
    "incumbent_pct": 26.18,
    "challenger_name": "Slavi Trifonov",
    "challenger_party": "ITN",
    "challenger_pct": 17.66,
    "electoral_system": "Parliamentary, proportional representation",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/April_2021_Bulgarian_parliamentary_election"
  },
  {
    "country": "Chad",
    "year": 2021,
    "election_type": "Presidential",
    "incumbent_name": "Idriss Déby",
    "incumbent_party": "MPS",
    "incumbent_pct": 79.32,
    "challenger_name": "Albert Pahimi Padacké",
    "challenger_party": "RNDT-Le Réveil",
    "challenger_pct": 10.32,
    "electoral_system": "Presidential, two-round",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2021_Chadian_presidential_election"
  },
  {
    "country": "Croatia",
    "year": 2016,
    "election_type": "Parliamentary",
    "incumbent_name": "Andrej Plenković",
    "incumbent_party": "HDZ",
    "incumbent_pct": 36.27,
    "challenger_name": "Zoran Milanović",
    "challenger_party": "SDP (People's Coalition)",
    "challenger_pct": 33.83,
    "electoral_system": "Parliamentary, proportional representation",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2016_Croatian_parliamentary_election"
  },
  {
    "country": "Croatia",
    "year": 2024,
    "election_type": "Parliamentary",
    "incumbent_name": "Andrej Plenković",
    "incumbent_party": "HDZ",
    "incumbent_pct": 34.32,
    "challenger_name": "Peđa Grbin",
    "challenger_party": "SDP (Rivers of Justice)",
    "challenger_pct": 25.4,
    "electoral_system": "Parliamentary, proportional representation",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2024_Croatian_parliamentary_election"
  },
  {
    "country": "Czechia",
    "year": 2021,
    "election_type": "Parliamentary",
    "incumbent_name": "Andrej Babiš",
    "incumbent_party": "ANO",
    "incumbent_pct": 27.12,
    "challenger_name": "Petr Fiala",
    "challenger_party": "SPOLU",
    "challenger_pct": 27.79,
    "electoral_system": "Parliamentary, proportional representation",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2021_Czech_parliamentary_election"
  },
  {
    "country": "Dominican Republic",
    "year": 2016,
    "election_type": "Presidential",
    "incumbent_name": "Danilo Medina",
    "incumbent_party": "PLD",
    "incumbent_pct": 61.74,
    "challenger_name": "Luis Abinader",
    "challenger_party": "PRM",
    "challenger_pct": 34.93,
    "electoral_system": "Presidential, qualified plurality",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2016_Dominican_Republic_general_election"
  },
  {
    "country": "Dominican Republic",
    "year": 2020,
    "election_type": "Presidential",
    "incumbent_name": "Gonzalo Castillo",
    "incumbent_party": "PLD",
    "incumbent_pct": 37.46,
    "challenger_name": "Luis Abinader",
    "challenger_party": "PRM",
    "challenger_pct": 52.52,
    "electoral_system": "Presidential, qualified plurality",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2020_Dominican_Republic_general_election"
  },
  {
    "country": "Ecuador",
    "year": 2009,
    "election_type": "Presidential",
    "incumbent_name": "Rafael Correa",
    "incumbent_party": "PAIS Alliance",
    "incumbent_pct": 51.99,
    "challenger_name": "Lucio Gutiérrez",
    "challenger_party": "PSP",
    "challenger_pct": 28.24,
    "electoral_system": "Presidential, two-round",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2009_Ecuadorian_general_election"
  },
  {
    "country": "Ecuador",
    "year": 2013,
    "election_type": "Presidential",
    "incumbent_name": "Rafael Correa",
    "incumbent_party": "PAIS Alliance",
    "incumbent_pct": 57.17,
    "challenger_name": "Guillermo Lasso",
    "challenger_party": "CREO",
    "challenger_pct": 22.68,
    "electoral_system": "Presidential, two-round",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2013_Ecuadorian_general_election"
  },
  {
    "country": "El Salvador",
    "year": 2024,
    "election_type": "Presidential",
    "incumbent_name": "Nayib Bukele",
    "incumbent_party": "Nuevas Ideas",
    "incumbent_pct": 84.65,
    "challenger_name": "Manuel Flores",
    "challenger_party": "FMLN",
    "challenger_pct": 6.4,
    "electoral_system": "Presidential, single round",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2024_Salvadoran_presidential_election"
  },
  {
    "country": "Ethiopia",
    "year": 2021,
    "election_type": "Parliamentary",
    "incumbent_name": "Abiy Ahmed",
    "incumbent_party": "Prosperity Party",
    "incumbent_pct": 96.3,
    "challenger_name": "NAMA",
    "challenger_party": "National Movement of Amhara",
    "challenger_pct": 1.15,
    "electoral_system": "Parliamentary, first-past-the-post",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2021_Ethiopian_general_election"
  },
  {
    "country": "Georgia",
    "year": 2008,
    "election_type": "Presidential",
    "incumbent_name": "Mikheil Saakashvili",
    "incumbent_party": "UNM",
    "incumbent_pct": 53.47,
    "challenger_name": "Levan Gachechiladze",
    "challenger_party": "Joint Opposition",
    "challenger_pct": 25.69,
    "electoral_system": "Presidential, two-round",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2008_Georgian_presidential_election"
  },
  {
    "country": "Ghana",
    "year": 2020,
    "election_type": "Presidential",
    "incumbent_name": "Nana Akufo-Addo",
    "incumbent_party": "NPP",
    "incumbent_pct": 51.6,
    "challenger_name": "John Dramani Mahama",
    "challenger_party": "NDC",
    "challenger_pct": 47.36,
    "electoral_system": "Presidential, first-past-the-post",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2020_Ghanaian_general_election"
  },
  {
    "country": "Ghana",
    "year": 2024,
    "election_type": "Presidential",
    "incumbent_name": "Mahamudu Bawumia",
    "incumbent_party": "NPP",
    "incumbent_pct": 41.61,
    "challenger_name": "John Dramani Mahama",
    "challenger_party": "NDC",
    "challenger_pct": 56.55,
    "electoral_system": "Presidential, first-past-the-post",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2024_Ghanaian_general_election"
  },
  {
    "country": "Greece",
    "year": 2023,
    "election_type": "Parliamentary",
    "incumbent_name": "Kyriakos Mitsotakis",
    "incumbent_party": "New Democracy",
    "incumbent_pct": 40.55,
    "challenger_name": "Alexis Tsipras",
    "challenger_party": "SYRIZA",
    "challenger_pct": 17.84,
    "electoral_system": "Parliamentary, reinforced proportional representation",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/June_2023_Greek_parliamentary_election"
  },
  {
    "country": "Guatemala",
    "year": 2023,
    "election_type": "Presidential",
    "incumbent_name": "Alejandro Giammattei",
    "incumbent_party": "Vamos",
    "incumbent_pct": null,
    "challenger_name": "Bernardo Arévalo",
    "challenger_party": "Movimiento Semilla",
    "challenger_pct": 58.01,
    "electoral_system": "Presidential, two-round",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2023_Guatemalan_general_election"
  },
  {
    "country": "Guinea",
    "year": 2020,
    "election_type": "Presidential",
    "incumbent_name": "Alpha Condé",
    "incumbent_party": "RPG",
    "incumbent_pct": 59.49,
    "challenger_name": "Cellou Dalein Diallo",
    "challenger_party": "UFDG",
    "challenger_pct": 33.5,
    "electoral_system": "Presidential, two-round",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2020_Guinean_presidential_election"
  },
  {
    "country": "Guyana",
    "year": 2020,
    "election_type": "Presidential",
    "incumbent_name": "David Granger",
    "incumbent_party": "APNU+AFC",
    "incumbent_pct": 47.34,
    "challenger_name": "Irfaan Ali",
    "challenger_party": "PPP/C",
    "challenger_pct": 50.69,
    "electoral_system": "Parliamentary, proportional representation",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2020_Guyanese_general_election"
  },
  {
    "country": "Honduras",
    "year": 2021,
    "election_type": "Presidential",
    "incumbent_name": "Nasry Asfura",
    "incumbent_party": "National Party",
    "incumbent_pct": 36.93,
    "challenger_name": "Xiomara Castro",
    "challenger_party": "LIBRE",
    "challenger_pct": 51.12,
    "electoral_system": "Presidential, first-past-the-post",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2021_Honduran_general_election"
  },
  {
    "country": "Hungary",
    "year": 2014,
    "election_type": "Parliamentary",
    "incumbent_name": "Viktor Orbán",
    "incumbent_party": "Fidesz-KDNP",
    "incumbent_pct": 44.87,
    "challenger_name": "Attila Mesterházy",
    "challenger_party": "Unity (MSZP-led alliance)",
    "challenger_pct": 25.67,
    "electoral_system": "Parliamentary, mixed (single-member districts + proportional list)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2014_Hungarian_parliamentary_election"
  },
  {
    "country": "Hungary",
    "year": 2018,
    "election_type": "Parliamentary",
    "incumbent_name": "Viktor Orbán",
    "incumbent_party": "Fidesz-KDNP",
    "incumbent_pct": 49.27,
    "challenger_name": "Gábor Vona",
    "challenger_party": "Jobbik",
    "challenger_pct": 19.06,
    "electoral_system": "Parliamentary, mixed (single-member districts + proportional list)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2018_Hungarian_parliamentary_election"
  },
  {
    "country": "Hungary",
    "year": 2022,
    "election_type": "Parliamentary",
    "incumbent_name": "Viktor Orbán",
    "incumbent_party": "Fidesz-KDNP",
    "incumbent_pct": 54.13,
    "challenger_name": "Péter Márki-Zay",
    "challenger_party": "United for Hungary",
    "challenger_pct": 35.04,
    "electoral_system": "Parliamentary, mixed (single-member districts + proportional list)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2022_Hungarian_parliamentary_election"
  },
  {
    "country": "India",
    "year": 2019,
    "election_type": "Parliamentary",
    "incumbent_name": "Narendra Modi",
    "incumbent_party": "BJP",
    "incumbent_pct": 37.36,
    "challenger_name": "Rahul Gandhi",
    "challenger_party": "INC",
    "challenger_pct": 19.49,
    "electoral_system": "Parliamentary, first-past-the-post",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2019_Indian_general_election"
  },
  {
    "country": "India",
    "year": 2024,
    "election_type": "Parliamentary",
    "incumbent_name": "Narendra Modi",
    "incumbent_party": "BJP",
    "incumbent_pct": 36.56,
    "challenger_name": "Rahul Gandhi",
    "challenger_party": "INC",
    "challenger_pct": 21.19,
    "electoral_system": "Parliamentary, first-past-the-post",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2024_Indian_general_election"
  },
  {
    "country": "Indonesia",
    "year": 2019,
    "election_type": "Presidential",
    "incumbent_name": "Joko Widodo",
    "incumbent_party": "PDI-P",
    "incumbent_pct": 55.5,
    "challenger_name": "Prabowo Subianto",
    "challenger_party": "Gerindra",
    "challenger_pct": 44.5,
    "electoral_system": "Presidential, first-past-the-post",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2019_Indonesian_general_election"
  },
  {
    "country": "Indonesia",
    "year": 2024,
    "election_type": "Presidential",
    "incumbent_name": "Prabowo Subianto",
    "incumbent_party": "Gerindra (ruling coalition)",
    "incumbent_pct": 58.59,
    "challenger_name": "Anies Baswedan",
    "challenger_party": "NasDem-led coalition",
    "challenger_pct": 24.95,
    "electoral_system": "Presidential, two-round",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2024_Indonesian_general_election"
  },
  {
    "country": "Lesotho",
    "year": 2017,
    "election_type": "Parliamentary",
    "incumbent_name": "Pakalitha Mosisili",
    "incumbent_party": "DC",
    "incumbent_pct": 25.0,
    "challenger_name": "Tom Thabane",
    "challenger_party": "ABC",
    "challenger_pct": 40.5,
    "electoral_system": "Parliamentary, mixed member proportional",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2017_Lesotho_general_election"
  },
  {
    "country": "Liberia",
    "year": 2017,
    "election_type": "Presidential",
    "incumbent_name": "Joseph Boakai",
    "incumbent_party": "Unity Party",
    "incumbent_pct": 38.5,
    "challenger_name": "George Weah",
    "challenger_party": "CDC",
    "challenger_pct": 61.5,
    "electoral_system": "Presidential, two-round",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2017_Liberian_general_election"
  },
  {
    "country": "Madagascar",
    "year": 2001,
    "election_type": "Presidential",
    "incumbent_name": "Didier Ratsiraka",
    "incumbent_party": "AREMA",
    "incumbent_pct": 40.89,
    "challenger_name": "Marc Ravalomanana",
    "challenger_party": "TIM",
    "challenger_pct": 51.46,
    "electoral_system": "Presidential, two-round",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/Malagasy_presidential_election,_2001"
  },
  {
    "country": "Malawi",
    "year": 2004,
    "election_type": "Presidential",
    "incumbent_name": "Bingu wa Mutharika",
    "incumbent_party": "UDF",
    "incumbent_pct": 35.97,
    "challenger_name": "John Tembo",
    "challenger_party": "MCP",
    "challenger_pct": 27.1,
    "electoral_system": "Presidential, first-past-the-post",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/Malawian_general_election,_2004"
  },
  {
    "country": "Malawi",
    "year": 2020,
    "election_type": "Presidential (re-run)",
    "incumbent_name": "Peter Mutharika",
    "incumbent_party": "DPP",
    "incumbent_pct": 39.4,
    "challenger_name": "Lazarus Chakwera",
    "challenger_party": "MCP",
    "challenger_pct": 58.57,
    "electoral_system": "Presidential, first-past-the-post",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2020_Malawian_presidential_election"
  },
  {
    "country": "Maldives",
    "year": 2018,
    "election_type": "Presidential",
    "incumbent_name": "Abdulla Yameen",
    "incumbent_party": "PPM",
    "incumbent_pct": 41.66,
    "challenger_name": "Ibrahim Mohamed Solih",
    "challenger_party": "MDP",
    "challenger_pct": 58.33,
    "electoral_system": "Presidential, first-past-the-post",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2018_Maldivian_presidential_election"
  },
  {
    "country": "Malta",
    "year": 2017,
    "election_type": "Parliamentary",
    "incumbent_name": "Joseph Muscat",
    "incumbent_party": "Labour",
    "incumbent_pct": 55.04,
    "challenger_name": "Simon Busuttil",
    "challenger_party": "Nationalist Party",
    "challenger_pct": 43.68,
    "electoral_system": "Parliamentary, single transferable vote",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2017_Maltese_general_election"
  },
  {
    "country": "Mauritania",
    "year": 2014,
    "election_type": "Presidential",
    "incumbent_name": "Mohamed Ould Abdel Aziz",
    "incumbent_party": "UPR",
    "incumbent_pct": 81.89,
    "challenger_name": "Biram Dah Abeid",
    "challenger_party": "Independent",
    "challenger_pct": 8.67,
    "electoral_system": "Presidential, two-round",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2014_Mauritanian_presidential_election"
  },
  {
    "country": "Mauritania",
    "year": 2019,
    "election_type": "Presidential",
    "incumbent_name": "Mohamed Ould Ghazouani",
    "incumbent_party": "UPR",
    "incumbent_pct": 52.01,
    "challenger_name": "Biram Dah Abeid",
    "challenger_party": "Independent",
    "challenger_pct": 18.58,
    "electoral_system": "Presidential, two-round",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2019_Mauritanian_presidential_election"
  },
  {
    "country": "Mauritania",
    "year": 2024,
    "election_type": "Presidential",
    "incumbent_name": "Mohamed Ould Ghazouani",
    "incumbent_party": "UPR",
    "incumbent_pct": 56.12,
    "challenger_name": "Biram Dah Abeid",
    "challenger_party": "Independent",
    "challenger_pct": 22.1,
    "electoral_system": "Presidential, two-round",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2024_Mauritanian_presidential_election"
  },
  {
    "country": "Mauritius",
    "year": 2019,
    "election_type": "Parliamentary",
    "incumbent_name": "Pravind Jugnauth",
    "incumbent_party": "MSM",
    "incumbent_pct": 37.69,
    "challenger_name": "Navin Ramgoolam",
    "challenger_party": "Labour Party (Alliance Nationale)",
    "challenger_pct": 33.83,
    "electoral_system": "Parliamentary, block vote",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2019_Mauritian_general_election"
  },
  {
    "country": "Mauritius",
    "year": 2024,
    "election_type": "Parliamentary",
    "incumbent_name": "Pravind Jugnauth",
    "incumbent_party": "MSM",
    "incumbent_pct": 27.8,
    "challenger_name": "Navin Ramgoolam",
    "challenger_party": "Labour Party (Alliance du Changement)",
    "challenger_pct": 62.6,
    "electoral_system": "Parliamentary, block vote",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2024_Mauritian_general_election"
  },
  {
    "country": "Mexico",
    "year": 2024,
    "election_type": "Presidential",
    "incumbent_name": "Claudia Sheinbaum",
    "incumbent_party": "Morena (Sigamos Haciendo Historia)",
    "incumbent_pct": 59.75,
    "challenger_name": "Xochitl Galvez",
    "challenger_party": "PAN-PRI-PRD (Fuerza y Corazon por Mexico)",
    "challenger_pct": 27.45,
    "electoral_system": "First-past-the-post",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2024_Mexican_general_election"
  },
  {
    "country": "Moldova",
    "year": 2001,
    "election_type": "Parliamentary",
    "incumbent_name": "Dumitru Braghis",
    "incumbent_party": "Braghis Alliance",
    "incumbent_pct": 13.36,
    "challenger_name": "Vladimir Voronin",
    "challenger_party": "PCRM (Party of Communists)",
    "challenger_pct": 50.07,
    "electoral_system": "Proportional representation",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2001_Moldovan_parliamentary_election"
  },
  {
    "country": "Moldova",
    "year": 2005,
    "election_type": "Parliamentary",
    "incumbent_name": "Vladimir Voronin",
    "incumbent_party": "PCRM (Party of Communists)",
    "incumbent_pct": 46.1,
    "challenger_name": "Serafim Urecheanu",
    "challenger_party": "Electoral Bloc Democratic Moldova (BEMD)",
    "challenger_pct": 28.53,
    "electoral_system": "Proportional representation",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2005_Moldovan_parliamentary_election"
  },
  {
    "country": "Moldova",
    "year": 2009,
    "election_type": "Parliamentary",
    "incumbent_name": "Vladimir Voronin",
    "incumbent_party": "PCRM (Party of Communists)",
    "incumbent_pct": 44.69,
    "challenger_name": "Vlad Filat",
    "challenger_party": "PLDM (Liberal Democratic Party)",
    "challenger_pct": 16.57,
    "electoral_system": "Proportional representation",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/July_2009_Moldovan_parliamentary_election"
  },
  {
    "country": "Moldova",
    "year": 2014,
    "election_type": "Parliamentary",
    "incumbent_name": "Iurie Leanca",
    "incumbent_party": "PLDM (Liberal Democratic Party) / Pro-European Coalition",
    "incumbent_pct": 20.16,
    "challenger_name": "Igor Dodon",
    "challenger_party": "PSRM (Party of Socialists)",
    "challenger_pct": 20.51,
    "electoral_system": "Proportional representation",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2014_Moldovan_parliamentary_election"
  },
  {
    "country": "Mongolia",
    "year": 2020,
    "election_type": "Parliamentary",
    "incumbent_name": "Ukhnaagiin Khurelsukh",
    "incumbent_party": "MPP (Mongolian People's Party)",
    "incumbent_pct": 44.9,
    "challenger_name": "Democratic Party",
    "challenger_party": "DP (Democratic Party)",
    "challenger_pct": null,
    "electoral_system": "Mixed (majoritarian single-member districts)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2020_Mongolian_legislative_election"
  },
  {
    "country": "Mongolia",
    "year": 2024,
    "election_type": "Parliamentary",
    "incumbent_name": "Luvsannamsrain Oyun-Erdene",
    "incumbent_party": "MPP (Mongolian People's Party)",
    "incumbent_pct": 35.0,
    "challenger_name": "Democratic Party",
    "challenger_party": "DP (Democratic Party)",
    "challenger_pct": null,
    "electoral_system": "Mixed (proportional and majoritarian)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2024_Mongolian_parliamentary_election"
  },
  {
    "country": "Mozambique",
    "year": 2019,
    "election_type": "Presidential",
    "incumbent_name": "Filipe Nyusi",
    "incumbent_party": "FRELIMO",
    "incumbent_pct": 73.0,
    "challenger_name": "Ossufo Momade",
    "challenger_party": "RENAMO",
    "challenger_pct": 21.88,
    "electoral_system": "First-past-the-post (two-round system not used; simple majority)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2019_Mozambican_general_election"
  },
  {
    "country": "Mozambique",
    "year": 2024,
    "election_type": "Presidential",
    "incumbent_name": "Daniel Chapo",
    "incumbent_party": "FRELIMO",
    "incumbent_pct": 65.17,
    "challenger_name": "Venancio Mondlane",
    "challenger_party": "PODEMOS (Independent/Opposition)",
    "challenger_pct": 24.19,
    "electoral_system": "First-past-the-post (simple majority)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2024_Mozambican_general_election"
  },
  {
    "country": "Namibia",
    "year": 2019,
    "election_type": "Presidential",
    "incumbent_name": "Hage Geingob",
    "incumbent_party": "SWAPO",
    "incumbent_pct": 56.3,
    "challenger_name": "Panduleni Itula",
    "challenger_party": "Independent",
    "challenger_pct": 29.4,
    "electoral_system": "First-past-the-post (majority required; two-round if needed)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2019_Namibian_general_election"
  },
  {
    "country": "Namibia",
    "year": 2024,
    "election_type": "Presidential",
    "incumbent_name": "Netumbo Nandi-Ndaitwah",
    "incumbent_party": "SWAPO",
    "incumbent_pct": 57.31,
    "challenger_name": "Panduleni Itula",
    "challenger_party": "IPC (Independent Patriots for Change)",
    "challenger_pct": 25.5,
    "electoral_system": "First-past-the-post (majority required; two-round if needed)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2024_Namibian_general_election"
  },
  {
    "country": "Nicaragua",
    "year": 2001,
    "election_type": "Presidential",
    "incumbent_name": "Daniel Ortega",
    "incumbent_party": "FSLN (Sandinista National Liberation Front)",
    "incumbent_pct": 42.3,
    "challenger_name": "Enrique Bolanos",
    "challenger_party": "PLC (Constitutionalist Liberal Party)",
    "challenger_pct": 56.3,
    "electoral_system": "Two-round system (35% threshold with 5% lead)",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2001_Nicaraguan_general_election"
  },
  {
    "country": "Nicaragua",
    "year": 2011,
    "election_type": "Presidential",
    "incumbent_name": "Daniel Ortega",
    "incumbent_party": "FSLN (Sandinista National Liberation Front)",
    "incumbent_pct": 62.46,
    "challenger_name": "Fabio Gadea",
    "challenger_party": "PLI (Independent Liberal Party)",
    "challenger_pct": 31.0,
    "electoral_system": "Two-round system (35% threshold with 5% lead)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2011_Nicaraguan_general_election"
  },
  {
    "country": "Nicaragua",
    "year": 2016,
    "election_type": "Presidential",
    "incumbent_name": "Daniel Ortega",
    "incumbent_party": "FSLN (Sandinista National Liberation Front)",
    "incumbent_pct": 72.44,
    "challenger_name": "Maximino Rodriguez",
    "challenger_party": "PLC (Constitutionalist Liberal Party)",
    "challenger_pct": 14.2,
    "electoral_system": "Two-round system (35% threshold with 5% lead; first-round win)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2016_Nicaraguan_general_election"
  },
  {
    "country": "Niger",
    "year": 2016,
    "election_type": "Presidential",
    "incumbent_name": "Mahamadou Issoufou",
    "incumbent_party": "PNDS-Tarayya",
    "incumbent_pct": 92.49,
    "challenger_name": "Hama Amadou",
    "challenger_party": "MODEN/FA Lumana",
    "challenger_pct": 7.51,
    "electoral_system": "Two-round system (runoff; opposition boycotted second round)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2016_Nigerien_general_election"
  },
  {
    "country": "Nigeria",
    "year": 2023,
    "election_type": "Presidential",
    "incumbent_name": "Bola Tinubu",
    "incumbent_party": "APC (All Progressives Congress)",
    "incumbent_pct": 36.61,
    "challenger_name": "Atiku Abubakar",
    "challenger_party": "PDP (People's Democratic Party)",
    "challenger_pct": 29.07,
    "electoral_system": "First-past-the-post (with geographic spread requirement)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2023_Nigerian_presidential_election"
  },
  {
    "country": "North Macedonia",
    "year": 2008,
    "election_type": "Parliamentary",
    "incumbent_name": "Nikola Gruevski",
    "incumbent_party": "VMRO-DPMNE",
    "incumbent_pct": 48.0,
    "challenger_name": "Radmila Sekerinska",
    "challenger_party": "SDSM (Social Democratic Union)",
    "challenger_pct": 23.0,
    "electoral_system": "Proportional representation (6 multi-member constituencies)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/Macedonian_parliamentary_election,_2008"
  },
  {
    "country": "North Macedonia",
    "year": 2011,
    "election_type": "Parliamentary",
    "incumbent_name": "Nikola Gruevski",
    "incumbent_party": "VMRO-DPMNE",
    "incumbent_pct": 39.0,
    "challenger_name": "Branko Crvenkovski",
    "challenger_party": "SDSM (Social Democratic Union)",
    "challenger_pct": 32.78,
    "electoral_system": "Proportional representation (6 multi-member constituencies)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2011_Macedonian_parliamentary_election"
  },
  {
    "country": "North Macedonia",
    "year": 2014,
    "election_type": "Parliamentary",
    "incumbent_name": "Nikola Gruevski",
    "incumbent_party": "VMRO-DPMNE",
    "incumbent_pct": 43.0,
    "challenger_name": "Zoran Zaev",
    "challenger_party": "SDSM (Social Democratic Union)",
    "challenger_pct": 25.34,
    "electoral_system": "Proportional representation (6 multi-member constituencies)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2014_Macedonian_general_election"
  },
  {
    "country": "Paraguay",
    "year": 2013,
    "election_type": "Presidential",
    "incumbent_name": "Efrain Alegre",
    "incumbent_party": "PLRA (Authentic Radical Liberal Party)",
    "incumbent_pct": 37.11,
    "challenger_name": "Horacio Cartes",
    "challenger_party": "ANR-Colorado Party",
    "challenger_pct": 45.8,
    "electoral_system": "First-past-the-post",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2013_Paraguayan_general_election"
  },
  {
    "country": "Philippines",
    "year": 2022,
    "election_type": "Presidential",
    "incumbent_name": "Ferdinand Marcos Jr.",
    "incumbent_party": "PFP (Party of Federal and Philippine Federalism) / UniTeam",
    "incumbent_pct": 58.77,
    "challenger_name": "Leni Robredo",
    "challenger_party": "Independent (Liberal Party chairperson)",
    "challenger_pct": 27.94,
    "electoral_system": "First-past-the-post (plurality)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2022_Philippine_presidential_election"
  },
  {
    "country": "Poland",
    "year": 2019,
    "election_type": "Parliamentary",
    "incumbent_name": "Mateusz Morawiecki",
    "incumbent_party": "PiS (Law and Justice)",
    "incumbent_pct": 43.59,
    "challenger_name": "Grzegorz Schetyna",
    "challenger_party": "KO (Civic Coalition)",
    "challenger_pct": 27.4,
    "electoral_system": "Proportional representation (d'Hondt method)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2019_Polish_parliamentary_election"
  },
  {
    "country": "Poland",
    "year": 2023,
    "election_type": "Parliamentary",
    "incumbent_name": "Mateusz Morawiecki",
    "incumbent_party": "PiS (Law and Justice)",
    "incumbent_pct": 35.38,
    "challenger_name": "Donald Tusk",
    "challenger_party": "KO (Civic Coalition)",
    "challenger_pct": 30.7,
    "electoral_system": "Proportional representation (d'Hondt method)",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2023_Polish_parliamentary_election"
  },
  {
    "country": "Portugal",
    "year": 2022,
    "election_type": "Parliamentary",
    "incumbent_name": "Antonio Costa",
    "incumbent_party": "PS (Socialist Party)",
    "incumbent_pct": 41.37,
    "challenger_name": "Rui Rio",
    "challenger_party": "PSD (Social Democratic Party)",
    "challenger_pct": 29.09,
    "electoral_system": "Proportional representation (d'Hondt method)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2022_Portuguese_legislative_election"
  },
  {
    "country": "Portugal",
    "year": 2024,
    "election_type": "Parliamentary",
    "incumbent_name": "Antonio Costa (PS)",
    "incumbent_party": "PS (Socialist Party)",
    "incumbent_pct": 28.0,
    "challenger_name": "Luis Montenegro",
    "challenger_party": "AD (Democratic Alliance: PSD-CDS-PP)",
    "challenger_pct": 28.83,
    "electoral_system": "Proportional representation (d'Hondt method)",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2024_Portuguese_legislative_election"
  },
  {
    "country": "Senegal",
    "year": 2024,
    "election_type": "Presidential",
    "incumbent_name": "Amadou Ba",
    "incumbent_party": "BBY (Benno Bokk Yakaar / APR coalition)",
    "incumbent_pct": 35.79,
    "challenger_name": "Bassirou Diomaye Faye",
    "challenger_party": "PASTEF",
    "challenger_pct": 54.28,
    "electoral_system": "Two-round system (majority required; won in first round)",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2024_Senegalese_presidential_election"
  },
  {
    "country": "Serbia",
    "year": 2014,
    "election_type": "Parliamentary",
    "incumbent_name": "Aleksandar Vučić",
    "incumbent_party": "SNS (Serbian Progressive Party)",
    "incumbent_pct": 48.35,
    "challenger_name": "Ivica Dačić",
    "challenger_party": "SPS (Socialist Party of Serbia)",
    "challenger_pct": 13.49,
    "electoral_system": "Proportional representation (single nationwide constituency, 5% threshold)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2014_Serbian_parliamentary_election"
  },
  {
    "country": "Serbia",
    "year": 2017,
    "election_type": "Presidential",
    "incumbent_name": "Aleksandar Vučić",
    "incumbent_party": "SNS (Serbian Progressive Party)",
    "incumbent_pct": 55.08,
    "challenger_name": "Saša Janković",
    "challenger_party": "Independent",
    "challenger_pct": 16.36,
    "electoral_system": "Two-round system (majority required for first-round win)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2017_Serbian_presidential_election"
  },
  {
    "country": "Serbia",
    "year": 2022,
    "election_type": "Presidential + Parliamentary",
    "incumbent_name": "Aleksandar Vučić",
    "incumbent_party": "SNS (Serbian Progressive Party)",
    "incumbent_pct": 58.59,
    "challenger_name": "Zdravko Ponoš",
    "challenger_party": "United for the Victory of Serbia (coalition)",
    "challenger_pct": 18.84,
    "electoral_system": "Presidential: Two-round system; Parliamentary: Proportional representation",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2022_Serbian_general_election"
  },
  {
    "country": "Sierra Leone",
    "year": 2023,
    "election_type": "Presidential",
    "incumbent_name": "Julius Maada Bio",
    "incumbent_party": "SLPP (Sierra Leone People's Party)",
    "incumbent_pct": 56.17,
    "challenger_name": "Samura Kamara",
    "challenger_party": "APC (All People's Congress)",
    "challenger_pct": 41.16,
    "electoral_system": "First-past-the-post (55% threshold to avoid runoff)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2023_Sierra_Leonean_general_election"
  },
  {
    "country": "Slovenia",
    "year": 2022,
    "election_type": "Parliamentary",
    "incumbent_name": "Janez Janša",
    "incumbent_party": "SDS (Slovenian Democratic Party)",
    "incumbent_pct": 23.48,
    "challenger_name": "Robert Golob",
    "challenger_party": "GS (Freedom Movement)",
    "challenger_pct": 34.45,
    "electoral_system": "Proportional representation (D'Hondt method, 4% threshold)",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2022_Slovenian_parliamentary_election"
  },
  {
    "country": "South Africa",
    "year": 2019,
    "election_type": "Parliamentary",
    "incumbent_name": "Cyril Ramaphosa",
    "incumbent_party": "ANC (African National Congress)",
    "incumbent_pct": 57.5,
    "challenger_name": "Mmusi Maimane",
    "challenger_party": "DA (Democratic Alliance)",
    "challenger_pct": 20.77,
    "electoral_system": "Proportional representation (closed party lists)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2019_South_African_general_election"
  },
  {
    "country": "South Korea",
    "year": 2022,
    "election_type": "Presidential",
    "incumbent_name": "Lee Jae-myung",
    "incumbent_party": "DP (Democratic Party of Korea, incumbent party)",
    "incumbent_pct": 47.83,
    "challenger_name": "Yoon Suk-yeol",
    "challenger_party": "PPP (People Power Party)",
    "challenger_pct": 48.56,
    "electoral_system": "First-past-the-post (single round, plurality)",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2022_South_Korean_presidential_election"
  },
  {
    "country": "Sri Lanka",
    "year": 2005,
    "election_type": "Presidential",
    "incumbent_name": "Mahinda Rajapaksa",
    "incumbent_party": "SLFP/UPFA (Sri Lanka Freedom Party / United People's Freedom Alliance)",
    "incumbent_pct": 50.29,
    "challenger_name": "Ranil Wickremesinghe",
    "challenger_party": "UNP (United National Party)",
    "challenger_pct": 48.43,
    "electoral_system": "Contingent vote (supplementary vote system)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2005_Sri_Lankan_presidential_election"
  },
  {
    "country": "Sri Lanka",
    "year": 2010,
    "election_type": "Presidential",
    "incumbent_name": "Mahinda Rajapaksa",
    "incumbent_party": "SLFP/UPFA (Sri Lanka Freedom Party / United People's Freedom Alliance)",
    "incumbent_pct": 57.88,
    "challenger_name": "Sarath Fonseka",
    "challenger_party": "NDF (New Democratic Front, opposition coalition)",
    "challenger_pct": 40.15,
    "electoral_system": "Contingent vote (supplementary vote system)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2010_Sri_Lankan_presidential_election"
  },
  {
    "country": "Tanzania",
    "year": 2005,
    "election_type": "Presidential",
    "incumbent_name": "Jakaya Kikwete",
    "incumbent_party": "CCM (Chama Cha Mapinduzi)",
    "incumbent_pct": 80.28,
    "challenger_name": "Ibrahim Lipumba",
    "challenger_party": "CUF (Civic United Front)",
    "challenger_pct": 11.68,
    "electoral_system": "First-past-the-post (plurality)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2005_Tanzanian_general_election"
  },
  {
    "country": "Togo",
    "year": 2020,
    "election_type": "Presidential",
    "incumbent_name": "Faure Gnassingbé",
    "incumbent_party": "UNIR (Union for the Republic)",
    "incumbent_pct": 70.78,
    "challenger_name": "Agbéyomé Kodjo",
    "challenger_party": "MPDD (Patriotic Movement for Democracy and Development)",
    "challenger_pct": 19.46,
    "electoral_system": "Two-round system (majority required for first-round win)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2020_Togolese_presidential_election"
  },
  {
    "country": "Turkey",
    "year": 2011,
    "election_type": "Parliamentary",
    "incumbent_name": "Recep Tayyip Erdoğan",
    "incumbent_party": "AKP (Justice and Development Party)",
    "incumbent_pct": 49.83,
    "challenger_name": "Kemal Kılıçdaroğlu",
    "challenger_party": "CHP (Republican People's Party)",
    "challenger_pct": 25.98,
    "electoral_system": "Proportional representation (D'Hondt method, 10% national threshold)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2011_Turkish_general_election"
  },
  {
    "country": "Turkey",
    "year": 2015,
    "election_type": "Parliamentary (November)",
    "incumbent_name": "Ahmet Davutoğlu",
    "incumbent_party": "AKP (Justice and Development Party)",
    "incumbent_pct": 49.5,
    "challenger_name": "Kemal Kılıçdaroğlu",
    "challenger_party": "CHP (Republican People's Party)",
    "challenger_pct": 25.32,
    "electoral_system": "Proportional representation (D'Hondt method, 10% national threshold)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/November_2015_Turkish_general_election"
  },
  {
    "country": "Turkey",
    "year": 2018,
    "election_type": "Presidential",
    "incumbent_name": "Recep Tayyip Erdoğan",
    "incumbent_party": "AKP (Justice and Development Party)",
    "incumbent_pct": 52.59,
    "challenger_name": "Muharrem İnce",
    "challenger_party": "CHP (Republican People's Party)",
    "challenger_pct": 30.64,
    "electoral_system": "Two-round system (majority required for first-round win)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2018_Turkish_presidential_election"
  },
  {
    "country": "Ukraine",
    "year": 1999,
    "election_type": "Presidential",
    "incumbent_name": "Leonid Kuchma",
    "incumbent_party": "Independent (supported by multiple parties)",
    "incumbent_pct": 56.25,
    "challenger_name": "Petro Symonenko",
    "challenger_party": "CPU (Communist Party of Ukraine)",
    "challenger_pct": 37.8,
    "electoral_system": "Two-round system (runoff result shown)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/1999_Ukrainian_presidential_election"
  },
  {
    "country": "Ukraine",
    "year": 2004,
    "election_type": "Presidential",
    "incumbent_name": "Viktor Yanukovych",
    "incumbent_party": "Party of Regions (government-backed successor)",
    "incumbent_pct": 44.2,
    "challenger_name": "Viktor Yushchenko",
    "challenger_party": "Our Ukraine (opposition coalition)",
    "challenger_pct": 51.99,
    "electoral_system": "Two-round system (re-run runoff result after Orange Revolution)",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2004_Ukrainian_presidential_election"
  },
  {
    "country": "United States of America",
    "year": 2020,
    "election_type": "Presidential",
    "incumbent_name": "Donald Trump",
    "incumbent_party": "Republican Party",
    "incumbent_pct": 46.86,
    "challenger_name": "Joe Biden",
    "challenger_party": "Democratic Party",
    "challenger_pct": 51.31,
    "electoral_system": "Electoral College (indirect election; 270 of 538 electoral votes needed)",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2020_United_States_presidential_election"
  },
  {
    "country": "Uruguay",
    "year": 2024,
    "election_type": "Presidential",
    "incumbent_name": "Álvaro Delgado",
    "incumbent_party": "Partido Nacional (National Party, Lacalle Pou's coalition successor)",
    "incumbent_pct": 45.87,
    "challenger_name": "Yamandú Orsi",
    "challenger_party": "Frente Amplio (Broad Front)",
    "challenger_pct": 49.84,
    "electoral_system": "Two-round system (runoff result shown; majority required in first round)",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2024_Uruguayan_general_election"
  },
  {
    "country": "Vanuatu",
    "year": 1995,
    "election_type": "Parliamentary",
    "incumbent_name": "Maxime Carlot Korman",
    "incumbent_party": "UMP (Union of Moderate Parties)",
    "incumbent_pct": null,
    "challenger_name": "Donald Kalpokas (Unity Front coalition)",
    "challenger_party": "VP (Vanua'aku Pati) / Unity Front",
    "challenger_pct": null,
    "electoral_system": "Single non-transferable vote (multi-member constituencies) and FPTP (single-member constituencies)",
    "outcome": "lost",
    "notes": "UMP won 17 seats; Unity Front won 20 seats (VP 13, MPP 5, TU 2). Serge Vohor (dissident UMP) became PM. Vote percentages not available for fragmented multi-member district system.",
    "source": "https://en.wikipedia.org/wiki/1995_Vanuatuan_general_election"
  },
  {
    "country": "Venezuela",
    "year": 2000,
    "election_type": "Presidential",
    "incumbent_name": "Hugo Chávez",
    "incumbent_party": "MVR (Fifth Republic Movement)",
    "incumbent_pct": 59.76,
    "challenger_name": "Francisco Arias Cárdenas",
    "challenger_party": "Causa R (La Causa Radical) / independent coalition",
    "challenger_pct": 37.52,
    "electoral_system": "First-past-the-post (plurality)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2000_Venezuelan_general_election"
  },
  {
    "country": "Venezuela",
    "year": 2006,
    "election_type": "Presidential",
    "incumbent_name": "Hugo Chávez",
    "incumbent_party": "MVR (Fifth Republic Movement)",
    "incumbent_pct": 62.84,
    "challenger_name": "Manuel Rosales",
    "challenger_party": "Un Nuevo Tiempo (A New Era)",
    "challenger_pct": 36.9,
    "electoral_system": "First-past-the-post (plurality)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2006_Venezuelan_presidential_election"
  },
  {
    "country": "Venezuela",
    "year": 2012,
    "election_type": "Presidential",
    "incumbent_name": "Hugo Chávez",
    "incumbent_party": "PSUV (United Socialist Party of Venezuela)",
    "incumbent_pct": 55.07,
    "challenger_name": "Henrique Capriles Radonski",
    "challenger_party": "MUD (Democratic Unity Roundtable coalition)",
    "challenger_pct": 44.31,
    "electoral_system": "First-past-the-post (plurality)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2012_Venezuelan_presidential_election"
  },
  {
    "country": "Venezuela",
    "year": 2013,
    "election_type": "Presidential",
    "incumbent_name": "Nicolás Maduro",
    "incumbent_party": "PSUV (United Socialist Party of Venezuela, Chávez successor)",
    "incumbent_pct": 50.61,
    "challenger_name": "Henrique Capriles Radonski",
    "challenger_party": "MUD (Democratic Unity Roundtable coalition)",
    "challenger_pct": 49.12,
    "electoral_system": "First-past-the-post (plurality)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2013_Venezuelan_presidential_election"
  },
  {
    "country": "Zambia",
    "year": 2015,
    "election_type": "Presidential (by-election)",
    "incumbent_name": "Edgar Lungu",
    "incumbent_party": "PF (Patriotic Front, ruling party successor after Sata's death)",
    "incumbent_pct": 48.33,
    "challenger_name": "Hakainde Hichilema",
    "challenger_party": "UPND (United Party for National Development)",
    "challenger_pct": 46.67,
    "electoral_system": "First-past-the-post (plurality; simple majority)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2015_Zambian_presidential_election"
  },
  {
    "country": "Zambia",
    "year": 2016,
    "election_type": "Presidential",
    "incumbent_name": "Edgar Lungu",
    "incumbent_party": "PF (Patriotic Front)",
    "incumbent_pct": 50.35,
    "challenger_name": "Hakainde Hichilema",
    "challenger_party": "UPND (United Party for National Development)",
    "challenger_pct": 47.63,
    "electoral_system": "Two-round system (50%+1 required; new constitutional provision from 2016)",
    "outcome": "won",
    "source": "https://en.wikipedia.org/wiki/2016_Zambian_general_election"
  },
  {
    "country": "Zambia",
    "year": 2021,
    "election_type": "Presidential",
    "incumbent_name": "Edgar Lungu",
    "incumbent_party": "PF (Patriotic Front)",
    "incumbent_pct": 38.71,
    "challenger_name": "Hakainde Hichilema",
    "challenger_party": "UPND (United Party for National Development)",
    "challenger_pct": 59.02,
    "electoral_system": "Two-round system (50%+1 required for first-round win)",
    "outcome": "lost",
    "source": "https://en.wikipedia.org/wiki/2021_Zambian_general_election"
  }
];
